"""
AI Patrol Briefing Generator.

Uses Claude (claude-haiku-4-5) to generate a concise, actionable
officer briefing from predictions, traffic, and anomaly data.

Falls back to a structured template if no ANTHROPIC_API_KEY is set.
"""

import logging
from datetime import datetime
import pandas as pd

from config import ANTHROPIC_API_KEY

logger = logging.getLogger(__name__)

DAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday",
             "Friday", "Saturday", "Sunday"]


def _format_top_zones(risk_df: pd.DataFrame, n: int = 5) -> str:
    lines = []
    for i, row in risk_df.head(n).iterrows():
        cong = row.get("congestion_pct", 0)
        lines.append(
            f"  {i+1}. Zone {row['h3_index'][:8]}... | "
            f"Risk score: {row['dynamic_risk']:.3f} | "
            f"Congestion: {cong:.0f}% | "
            f"Watch for: {row.get('top_violation','N/A')} by {row.get('top_vehicle','N/A')}"
        )
    return "\n".join(lines)


def _format_anomalies(anomalies: pd.DataFrame, n: int = 3) -> str:
    if anomalies.empty:
        return "  None detected for this time slot."
    lines = []
    for _, row in anomalies.head(n).iterrows():
        lines.append(f"  ⚠ {row.get('alert_reason', 'Anomalous activity detected')}")
    return "\n".join(lines)


def _format_patrol_plan(plans: list) -> str:
    if not plans:
        return "  No patrol plan generated."
    lines = []
    for plan in plans:
        lines.append(f"  Officer {plan['officer']} ({plan['n_zones']} stops, ~{plan['total_travel_min']:.0f} min total):")
        for _, row in plan["route"].iterrows():
            lines.append(
                f"    Stop {row['stop']} at {row['arrival_time']} — "
                f"{row.get('top_violation','N/A')} zone "
                f"(congestion {row.get('congestion_pct',0):.0f}%)"
            )
    return "\n".join(lines)


def _template_briefing(now: datetime, risk_df: pd.DataFrame,
                        anomalies: pd.DataFrame, plans: list,
                        traffic_source: str) -> str:
    top_zone = risk_df.iloc[0] if not risk_df.empty else None
    return f"""PATROL BRIEFING — {now.strftime('%A, %d %B %Y %H:%M IST')}
{'='*60}

SITUATION SUMMARY
  Traffic data source : {traffic_source.upper()}
  High-risk zones now : {len(risk_df)}
  Active anomaly alerts: {len(anomalies)}

TOP PRIORITY ZONES (next 6 hours)
{_format_top_zones(risk_df)}

ANOMALY ALERTS (unusual activity for this time slot)
{_format_anomalies(anomalies)}

RECOMMENDED PATROL ROUTES
{_format_patrol_plan(plans)}

ACTION PRIORITIES
  • Focus on double-parking and main-road violations — highest traffic impact
  • Heavy vehicles (trucks, buses) should be priority targets
  • Peak enforcement window: deploy by {now.strftime('%H')}:00, maximum impact before next hour
  • Zones with congestion >50% need immediate attention

---
Generated by GridLock AI | Data: Bengaluru Traffic Police (Nov 2023–May 2024)
"""


def _llm_briefing(now: datetime, risk_df: pd.DataFrame,
                   anomalies: pd.DataFrame, plans: list,
                   traffic_source: str) -> str:
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

        context = f"""
Current time: {now.strftime('%A %d %B %Y, %H:%M IST')}
Traffic source: {traffic_source}

TOP 5 HIGH-RISK ZONES RIGHT NOW:
{_format_top_zones(risk_df, 5)}

ANOMALY ALERTS:
{_format_anomalies(anomalies, 3)}

PATROL PLAN:
{_format_patrol_plan(plans)}
"""

        message = client.messages.create(
            model      = "claude-haiku-4-5-20251001",
            max_tokens = 600,
            messages   = [{
                "role":    "user",
                "content": (
                    "You are an AI system briefing Bengaluru Traffic Police officers. "
                    "Generate a concise, action-oriented patrol briefing that an officer "
                    "can read in under 30 seconds. Use plain language. "
                    "Include: what to prioritise, where to go first, what vehicle types "
                    "and violation types to watch for. Be specific about times and locations.\n\n"
                    + context
                ),
            }],
        )
        return message.content[0].text

    except Exception as e:
        logger.warning("LLM briefing failed: %s — using template", e)
        return _template_briefing(now, risk_df, anomalies, plans, traffic_source)


def generate_briefing(risk_df: pd.DataFrame,
                       anomalies: pd.DataFrame,
                       plans: list,
                       traffic_source: str = "simulated") -> str:
    """
    Generate a patrol briefing. Uses Claude API if ANTHROPIC_API_KEY is set,
    otherwise falls back to a structured template.
    """
    now = datetime.now()

    if ANTHROPIC_API_KEY:
        return _llm_briefing(now, risk_df, anomalies, plans, traffic_source)

    return _template_briefing(now, risk_df, anomalies, plans, traffic_source)
